name: Deploy V2

on:
  push:
    tags:
      - 'v2.*'

jobs:
  deploy:
    uses: venkats56/terraform-azure/.github/workflows/reusable-terraform.yml@main
    with:
      tf_directory: terraform/v2
    secrets: inherit