name: Deploy V1

on:
  push:
    tags:
      - 'v1.*'

jobs:
  deploy:
    uses:  venkats56/terraform-azure/.github/workflows/reusable-terraform.yml@main
    with:
      tf_directory: terraform/v1
    secrets: inherit